import Link from 'next/link';
import Image from 'next/image';

export default async function TermsPage({ params }: { params: Promise<{ lang: 'en' | 'fr' }> }) {
  const { lang } = await params;
  
  const termsContent = {
    en: {
      title: "Terms of Service",
      lastUpdated: "Last updated: April 27, 2025",
      sections: [
        {
          title: "1. Service Description",
          content: "The Service enables users to generate analysis reports to validate their business ideas using artificial intelligence. Each generated report includes multiple analysis sections. By default, generated reports are partial and certain sections are not accessible. Users must purchase report credits to unlock all sections and access the complete analysis."
        },
        {
          title: "2. Registration and User Account",
          content: "Using the Service requires creating a user account. You agree to provide accurate, complete, and up-to-date information during registration. You are responsible for maintaining the confidentiality of your login credentials and all activities conducted under your account. You must immediately notify us of any unauthorized use of your account or security breach."
        },
        {
          title: "3. Report and Credit System",
          content: "The Service operates on a report credit system. Each credit allows users to unlock one complete report. Users can generate partial reports for free but must use a credit to access all analysis sections. The number of available reports is linked to the number of credits purchased and available in the user's account."
        },
        {
          title: "4. Pricing and Payment",
          content: "Report credits are sold according to our current pricing schedule available on our website. Prices are displayed in euros, including all applicable taxes. Payment is processed via credit card or any other payment method accepted by our platform. Report unlocking is immediate upon payment confirmation."
        },
        {
          title: "5. No Refund Policy",
          content: "Purchased report credits are non-refundable. Once purchased, credits remain available in your account until used, with no expiration date. This no-refund policy applies in all circumstances, including purchase errors, dissatisfaction with analysis results, or discontinuation of Service use."
        },
        {
          title: "6. Service Usage",
          content: "You agree to use the Service only for lawful purposes and in accordance with these Terms. You must not use the Service in any way that could damage, disable, overburden, or impair our servers or networks. You must not attempt to gain unauthorized access to any part of the Service, other users' accounts, or computer systems connected to the Service."
        },
        {
          title: "7. Intellectual Property",
          content: "The Service, including but not limited to source code, algorithms, user interface, design, text, graphics, and all other content, is protected by intellectual property laws. You retain ownership of the data you submit for analysis but grant us a non-exclusive license to use this data for Service provision purposes."
        },
        {
          title: "8. Results and Analysis",
          content: "Reports and analysis generated by artificial intelligence are provided for informational purposes only. We do not guarantee the accuracy, completeness, or relevance of the results. Decisions made based on generated analysis are your sole responsibility. We disclaim any liability for direct or indirect consequences arising from the use of generated reports."
        },
        {
          title: "9. Limitation of Liability",
          content: "To the extent permitted by law, our liability is limited to the amount you paid for report credits during the last twelve months. We are not responsible for indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities."
        },
        {
          title: "10. Service Availability",
          content: "We strive to maintain continuous Service availability. However, we do not guarantee uninterrupted or error-free access. Interruptions may occur for maintenance, updates, or due to circumstances beyond our control. We are not responsible for the consequences of such interruptions."
        },
        {
          title: "11. Privacy and Data Protection",
          content: "The collection and processing of your personal data are governed by our Privacy Policy, which forms an integral part of these Terms. We commit to protecting your data privacy and complying with applicable data protection regulations."
        },
        {
          title: "12. Terms Modifications",
          content: "We reserve the right to modify these Terms at any time. Modifications become effective upon publication on our website. Your continued use of the Service after publication of modifications constitutes acceptance of the new terms."
        },
        {
          title: "13. Termination",
          content: "We may suspend or terminate your access to the Service for violation of these Terms, without notice or refund of unused credits. You may terminate your account at any time, but unused credits will be forfeited without refund."
        },
        {
          title: "14. Applicable Law and Jurisdiction",
          content: "These Terms are governed by French law. Any dispute relating to their interpretation or execution falls under the exclusive jurisdiction of French courts, unless otherwise required by consumer protection laws."
        },
        {
          title: "15. Contact",
          content: "For any questions regarding these Terms or the Service, you may contact us at: support@womi-validateidea.com."
        }
      ]
    },
    fr: {
      title: "Conditions Générales d'Utilisation",
      lastUpdated: "Dernière mise à jour : 27 avril 2025",
      sections: [
        {
          title: "1. Description du Service",
          content: "Le Service permet aux utilisateurs de générer des rapports d'analyse pour valider leurs idées de business grâce à l'intelligence artificielle. Chaque rapport généré comprend plusieurs sections d'analyse. Par défaut, les rapports générés sont partiels et certaines sections ne sont pas accessibles. L'utilisateur doit acheter des crédits de rapports pour débloquer l'intégralité des sections et accéder à l'analyse complète."
        },
        {
          title: "2. Inscription et Compte Utilisateur",
          content: "L'utilisation du Service nécessite la création d'un compte utilisateur. Vous vous engagez à fournir des informations exactes, complètes et à jour lors de votre inscription. Vous êtes responsable de maintenir la confidentialité de vos identifiants de connexion et de toutes les activités réalisées sous votre compte. Vous devez nous informer immédiatement de toute utilisation non autorisée de votre compte ou de toute violation de sécurité."
        },
        {
          title: "3. Système de Rapports et Crédits",
          content: "Le Service fonctionne selon un système de crédits de rapports. Chaque crédit permet de débloquer un rapport complet. Les utilisateurs peuvent générer des rapports partiels gratuitement, mais doivent utiliser un crédit pour accéder à l'ensemble des sections d'analyse. Le nombre de rapports disponibles est lié au nombre de crédits achetés et disponibles sur le compte utilisateur."
        },
        {
          title: "4. Tarification et Paiement",
          content: "Les crédits de rapports sont vendus selon notre grille tarifaire en vigueur, disponible sur notre site. Les prix sont indiqués en euros toutes taxes comprises. Le paiement s'effectue par carte bancaire ou tout autre moyen de paiement accepté par notre plateforme. Le déblocage des rapports est immédiat après confirmation du paiement."
        },
        {
          title: "5. Politique de Non-Remboursement",
          content: "Les crédits de rapports achetés ne sont pas remboursables. Une fois l'achat effectué, les crédits restent disponibles sur votre compte jusqu'à leur utilisation, sans limitation de durée. Cette politique de non-remboursement s'applique dans toutes les circonstances, y compris en cas d'erreur d'achat, d'insatisfaction concernant les résultats des analyses ou de cessation d'utilisation du Service."
        },
        {
          title: "6. Utilisation du Service",
          content: "Vous vous engagez à utiliser le Service uniquement à des fins légales et conformément aux présentes CGU. Vous ne devez pas utiliser le Service d'une manière qui pourrait endommager, désactiver, surcharger ou altérer nos serveurs ou réseaux. Vous ne devez pas tenter d'obtenir un accès non autorisé à toute partie du Service, aux comptes d'autres utilisateurs ou aux systèmes informatiques connectés au Service."
        },
        {
          title: "7. Propriété Intellectuelle",
          content: "Le Service, incluant mais sans s'y limiter, le code source, les algorithmes, l'interface utilisateur, le design, les textes, les graphiques et tous les autres contenus, sont protégés par les lois sur la propriété intellectuelle. Vous conservez la propriété des données que vous soumettez pour analyse, mais nous accordez une licence non exclusive pour utiliser ces données aux fins de fourniture du Service."
        },
        {
          title: "8. Résultats et Analyses",
          content: "Les rapports et analyses générés par l'intelligence artificielle sont fournis à titre informatif uniquement. Nous ne garantissons pas l'exactitude, l'exhaustivité ou la pertinence des résultats. Les décisions prises sur la base des analyses générées relèvent de votre seule responsabilité. Nous déclinons toute responsabilité quant aux conséquences directes ou indirectes découlant de l'utilisation des rapports générés."
        },
        {
          title: "9. Limitation de Responsabilité",
          content: "Dans les limites autorisées par la loi, notre responsabilité est limitée au montant que vous avez payé pour les crédits de rapports au cours des douze derniers mois. Nous ne sommes pas responsables des dommages indirects, incidents, spéciaux, consécutifs ou punitifs, y compris les pertes de profits, de données ou d'opportunités commerciales."
        },
        {
          title: "10. Disponibilité du Service",
          content: "Nous nous efforçons de maintenir le Service disponible en permanence. Cependant, nous ne garantissons pas un accès ininterrompu ou sans erreur. Des interruptions peuvent survenir pour maintenance, mises à jour ou en raison de circonstances indépendantes de notre volonté. Nous ne sommes pas responsables des conséquences de ces interruptions."
        },
        {
          title: "11. Confidentialité et Protection des Données",
          content: "La collecte et le traitement de vos données personnelles sont régis par notre Politique de Confidentialité, qui fait partie intégrante des présentes CGU. Nous nous engageons à protéger la confidentialité de vos données et à respecter la réglementation applicable en matière de protection des données personnelles."
        },
        {
          title: "12. Modifications des CGU",
          content: "Nous nous réservons le droit de modifier ces CGU à tout moment. Les modifications entrent en vigueur dès leur publication sur notre site. Votre utilisation continue du Service après la publication des modifications constitue votre acceptation des nouvelles conditions."
        },
        {
          title: "13. Résiliation",
          content: "Nous pouvons suspendre ou résilier votre accès au Service en cas de violation des présentes CGU, sans préavis ni remboursement des crédits non utilisés. Vous pouvez résilier votre compte à tout moment, mais les crédits non utilisés seront perdus et ne feront l'objet d'aucun remboursement."
        },
        {
          title: "14. Droit Applicable et Juridiction",
          content: "Les présentes CGU sont régies par le droit français. Tout litige relatif à leur interprétation ou leur exécution relève de la compétence exclusive des tribunaux français, sauf disposition légale contraire applicable aux consommateurs."
        },
        {
          title: "15. Contact",
          content: "Pour toute question concernant ces CGU ou le Service, vous pouvez nous contacter à l'adresse email : support@womi-validateidea.com."
        }
      ]
    }
  };

  const content = lang === 'fr' ? termsContent.fr : termsContent.en;

  return (
    <main className="min-h-screen w-full p-0 flex flex-col relative">
      <header className="flex justify-between items-center px-4 md:px-5 py-4 border-b border-gray-200">
        {/* Logo */}
        <Link href={`/${lang}`} className="flex items-center">
          <Image 
            src="/icon/logo.svg" 
            alt="Womi logo" 
            width={60} 
            height={60} 
          />
          <div className="flex flex-col">
            <span className="text-2xl font-bold ml-2">Womi</span>
          </div>
        </Link>
      </header>

      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <h1 className="text-3xl md:text-4xl font-bold mb-4">{content.title}</h1>
        <p className="text-gray-500 mb-8">{content.lastUpdated}</p>

        <div className="space-y-8">
          {content.sections.map((section, index) => (
            <div key={index} className="border-b border-gray-200 pb-6 last:border-none">
              <h2 className="text-xl font-bold mb-4">{section.title}</h2>
              <p className="text-gray-700">{section.content}</p>
            </div>
          ))}
        </div>

        <div className="mt-12 text-center">
          <Link href={`/${lang}`} className="text-primary hover:underline">
            {lang === 'fr' ? 'Retour à l\'accueil' : 'Back to home'}
          </Link>
        </div>
      </div>

      <footer className="bg-gray-800 text-white py-8 mt-auto">
        <div className="container mx-auto px-4 text-center">
          <p>&copy; {new Date().getFullYear()} Womi. {lang === 'fr' ? 'Tous droits réservés.' : 'All rights reserved.'}</p>
          <div className="mt-4 flex justify-center space-x-4">
            <Link href={`/${lang}/terms`} className="hover:text-primary transition-colors">
              {lang === 'fr' ? 'Conditions d\'utilisation' : 'Terms of use'}
            </Link>
            <Link href={`/${lang}/privacy`} className="hover:text-primary transition-colors">
              {lang === 'fr' ? 'Politique de confidentialité' : 'Privacy policy'}
            </Link>
          </div>
        </div>
      </footer>
    </main>
  );
} 