import type { Metadata } from "next";
import { ThemeProvider } from "@/components/shared";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { Bricolage_Grotesque, Bellefair } from "next/font/google";
import PlausibleProvider from "next-plausible";
import { RootProvider } from "fumadocs-ui/provider";

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});
const bellefair = Bellefair({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <PlausibleProvider
          domain={process.env.NEXT_PUBLIC_BASE_DOMAIN || ""}
          trackOutboundLinks={true}
          taggedEvents={true}
          trackLocalhost={true}
        />
      </head>
      <body className={`antialiased ${bricolage.variable} ${bellefair.variable} font-sans`}>
        <RootProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            {children}
            <Toaster richColors position="top-right" />
          </ThemeProvider>
        </RootProvider>
      </body>
    </html>
  );
}
